spring:
  datasource:
    name: test
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/exam_demo?serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
  thymeleaf:
    cache: false
    mode: LEGACYHTML5

#-----------------------------------------------
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.exam.qc.bean.entity.po

server:
  port: 8088

